### ISSUE TITLE
Pinch-Zoom example incomplete

### ISSUE THREAD

**Issue by ghost** [GameTemplates/GDevelop-Examples#2]
It seems that the pinch-zoom example is incomplete... It doesn't change the zoom at all, and the IDs shown don't seem to be correct.

**Comment by ghost** [comment]
Here's an updated version I made. It's still not complete (no zooming still), but it fixes some issues with the touch markers (namely a typo with the Y values and the fact that the first touch has an ID of '0' (so no touch needs an ID of '-1')).

[game.json.zip](https://github.com/GameTemplates/GDevelop-Examples/files/2751001/game.json.zip)

**Comment by GameTemplates** [comment]
Thanks, it was uploaded by mistake actually, I don't even know what this project was.
