### ISSUE TITLE
Prevent multi selection from group of items

### ISSUE THREAD

**Issue by khaleehh** [GameTemplates/GDevelop-Examples#4]
Hi,
I took card game and i customized it,
When the game starts the placeholder randomized the cards:
[image1](https://forum.gdevelop-app.com/uploads/default/original/2X/b/b619f752324cf653ff0685554ea154da3623c7fa.jpeg)

The issue is that i have group of 5 cards and the user should click and chose only one card … but i can see the user can also click and open the other cards …
[image2](https://forum.gdevelop-app.com/uploads/default/original/2X/b/b619f752324cf653ff0685554ea154da3623c7fa.jpeg)

how i will make it if the user already selected one card! the other cards from the same group will not be clickable …
[image3](https://forum.gdevelop-app.com/uploads/default/optimized/2X/6/6e43612f60a1d7286382d0b78426d405ad151e5b_2_690x199.jpeg)

**Comment by GameTemplates** [comment]
Sorry for the late reply, I don't have any card games included in this repo, in case you are referring to the memory card game shipped with GDevelop, you may want to post this in their issue tracker if you haven't already:
https://github.com/4ian/GDevelop/issues
